# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-09 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20191109_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='name',
        ),
    ]
