# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20191109_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='reasoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('users', models.IntegerField(default=0)),
            ],
        ),
    ]
